services:
  - type: web
    name: fintra-backend
    env: java
    buildCommand: "./mvnw clean install"
    startCommand: "java -jar target/*.jar"
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
